server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gapiazza/DH.CTD.BK.Backend1.git
          default-label: sb
          force-pull: true
          search-paths: configData/parcial1